### ISSUE TITLE
Method definition syntax standard?

### ISSUE THREAD

**Issue by rye** [WLCSC/firefight2#13]
There are a variety of method definition syntaxes in usage currently. I observed the following differing varieties in `app/models/ticket.rb`:

The first variety uses no parentheses, a look that I both am intrigued by and enjoy:

``` ruby
# Line 39 as of 2af84a53ec9d14b068bdbdb5393c4cd8d3d8151c
def tagged_related_tickets recurse = true
```

The second variety uses parentheses, a look that I perceive to be more traditional and that makes me feel more safe:

``` ruby
# Line 28 as of 2af84a53ec9d14b068bdbdb5393c4cd8d3d8151c
def self.readable_by(user)
```

So, which one would we like to use? Personally, I prefer the first one over the second, simply because it feels more modern and hip, but I can see why we might want to use the second. I'd like not to mix them if we don't have to. The second seems more readable to me, but I'm not sure, hence my question.

If a standard is specified, I'll go ahead and go make sure everything conforms to it.

**Comment by Sammidysam** [comment]
Check out the second bullet point.
https://github.com/bbatsov/ruby-style-guide#syntax

**Comment by rye** [comment]
@btgeek, would you like to use that syntax throughout the models and elsewhere? As I said, I'll go and do that. Also, I might as well make the entire codebase comply with that specification while I'm at it.

**Comment by braddoeswebdev** [comment]
Go for it!

**Comment by rye** [comment]
All right. I'll close this issue for now and create a branch called `standard-conformance` for all work on it.
